// Local symptom-checker knowledge base: a curated vocabulary of common
// symptoms plus a set of common conditions they map to. This is a static,
// hand-authored reference table — NOT a trained model and NOT a live AI
// call. It exists so the "Symptom Checker" feature works fully offline with
// no API key, while remaining upfront about what's actually running it (see
// SourceBadge usage in symptom-checker.ts / the UI): when ANTHROPIC_API_KEY
// is configured, the same feature switches to a real LLM call automatically
// (src/lib/llm.ts, generateSymptomCheck) — this file only backs the fallback
// path. Never present this database as "AI" in the UI; label it plainly as
// a local knowledge base, matching the LLM/LOCAL badge pattern used
// everywhere else in the app.
//
// This is an informational self-check tool, not a diagnostic instrument —
// every condition entry carries plain-language advice, and the UI wraps all
// of this in a "not a medical diagnosis" disclaimer.

export type SymptomCategory =
  | "General"
  | "Respiratory"
  | "Cardiovascular"
  | "Digestive"
  | "Neurological"
  | "Musculoskeletal"
  | "Skin"
  | "ENT & Eye"
  | "Urinary & Reproductive"
  | "Mental health"
  | "Endocrine & Metabolic"
  | "Allergy & Immune"
  | "Sleep"
  | "Pediatric";

export const SYMPTOM_CATEGORIES: Record<SymptomCategory, string[]> = {
  General: [
    "fever", "high fever", "low-grade fever", "chills", "night sweats", "fatigue",
    "weakness", "general malaise", "loss of appetite", "unexplained weight loss",
    "unexplained weight gain", "excessive thirst", "excessive hunger", "dehydration",
    "excessive sweating", "cold intolerance", "heat intolerance", "generalized body ache",
    "lethargy", "irritability", "difficulty waking up", "feeling faint", "fainting",
    "dizziness", "lightheadedness", "swollen lymph nodes", "restlessness",
    "generalized itching without rash", "excessive yawning", "cold sweats",
    "poor sleep", "generalized swelling",
  ],
  Respiratory: [
    "cough", "dry cough", "productive cough", "coughing up blood", "wheezing",
    "shortness of breath", "difficulty breathing", "chest tightness", "rapid breathing",
    "nasal congestion", "runny nose", "sneezing", "postnasal drip",
    "loss of sense of smell", "sore throat", "hoarseness", "painful swallowing",
    "snoring", "sinus pressure", "sinus headache", "nosebleed", "hiccups",
    "frequent throat clearing", "whistling sound while breathing", "chest congestion",
    "barking cough", "shallow breathing", "recurrent sneezing", "laryngitis",
  ],
  Cardiovascular: [
    "chest pain", "chest pressure", "chest pain radiating to arm", "palpitations",
    "rapid heartbeat", "irregular heartbeat", "slow heartbeat", "swelling in legs",
    "swelling in ankles", "leg cramps at night", "cold hands and feet",
    "bluish lips or fingertips", "fainting during exercise", "exercise intolerance",
    "varicose veins", "high blood pressure readings", "calf pain",
  ],
  Digestive: [
    "nausea", "vomiting", "vomiting blood", "diarrhea", "bloody stool",
    "black tarry stool", "constipation", "abdominal pain", "lower abdominal pain",
    "upper abdominal pain", "abdominal cramping", "bloating", "excessive gas",
    "heartburn", "acid reflux", "indigestion", "difficulty swallowing food",
    "stomach growling", "belching", "early feeling of fullness", "rectal bleeding",
    "hemorrhoids", "anal itching", "yellowing of skin", "yellowing of eyes",
    "dark-colored urine", "pale-colored stool", "abdominal swelling",
    "food intolerance", "lactose intolerance", "unexplained weight loss with poor appetite",
    "stomach cramps after eating", "burping up food", "metallic taste in mouth",
    "gas after eating", "acid taste in mouth",
  ],
  Neurological: [
    "headache", "migraine", "severe sudden headache", "vertigo", "fainting spells",
    "seizure", "tremor", "numbness in limbs", "tingling sensation",
    "weakness on one side of body", "facial drooping", "slurred speech",
    "sudden confusion", "memory loss", "difficulty concentrating", "loss of balance",
    "difficulty walking", "muscle twitching", "sensitivity to light",
    "sensitivity to sound", "blurred vision", "double vision", "ringing in ears",
    "loss of consciousness", "pins and needles sensation",
  ],
  Musculoskeletal: [
    "joint pain", "joint swelling", "joint stiffness in the morning", "muscle pain",
    "muscle cramps", "muscle weakness", "lower back pain", "upper back pain",
    "neck pain", "neck stiffness", "shoulder pain", "knee pain", "hip pain",
    "difficulty moving a joint", "limited range of motion", "bone pain",
    "swelling in a limb", "bruising easily", "muscle spasm", "tendon pain",
    "foot pain", "heel pain", "wrist pain", "joint redness", "joint warmth to touch",
    "cracking joints", "clicking joint", "muscle stiffness after rest",
    "ankle pain", "elbow pain",
  ],
  Skin: [
    "skin rash", "itching", "hives", "dry skin", "oily skin", "acne breakouts",
    "skin redness", "skin peeling", "blisters", "skin discoloration",
    "unexplained bruising", "hair loss", "brittle nails", "nail discoloration",
    "new or changing mole", "non-healing skin wound", "painful boil", "cold sores",
    "skin cracking between toes", "jock itch", "athlete's foot",
    "warm and swollen skin patch", "eczema flare-up", "spider veins", "skin tags",
    "excessive dandruff", "chapped lips", "scalp itching", "sunburn",
  ],
  "ENT & Eye": [
    "ear pain", "ear discharge", "hearing loss", "feeling of ear fullness",
    "eye redness", "eye pain", "eye discharge", "itchy eyes", "watery eyes",
    "dry eyes", "eyelid swelling", "gritty feeling in eyes", "mouth ulcers",
    "bad breath", "bleeding gums", "toothache", "jaw pain",
    "difficulty opening mouth wide", "eye strain", "crusty eyelids",
  ],
  "Urinary & Reproductive": [
    "frequent urination", "painful urination", "urgent need to urinate",
    "blood in urine", "cloudy urine", "urinary incontinence", "difficulty urinating",
    "weak urine stream", "low urine output", "flank pain", "testicular pain",
    "testicular swelling", "vaginal discharge", "vaginal itching",
    "abnormal vaginal bleeding", "irregular menstrual periods",
    "unusually heavy periods", "missed period", "painful menstrual cramps",
    "pelvic pain", "erectile difficulty", "breast pain", "breast lump",
    "groin pain", "pain during intercourse", "lower abdominal pain in women",
    "burning sensation during urination", "lower back pain with urination",
    "spotting between periods", "nipple discharge",
  ],
  "Mental health": [
    "anxiety", "excessive worry", "panic attacks", "persistent low mood",
    "sadness lasting weeks", "mood swings", "difficulty falling asleep",
    "waking up frequently at night", "oversleeping", "loss of interest in activities",
    "social withdrawal", "racing thoughts", "feeling overwhelmed",
    "panic when in crowds", "constant fatigue despite rest", "crying spells",
    "trouble relaxing", "obsessive thoughts",
  ],
  "Endocrine & Metabolic": [
    "excessive thirst", "frequent urination at night", "unexplained weight loss",
    "unexplained weight gain", "cold intolerance", "heat intolerance",
    "hair thinning", "hand tremor", "excessive sweating without exertion",
    "fatigue after meals", "slow wound healing", "increased hunger",
  ],
  "Allergy & Immune": [
    "sneezing fits", "itchy watery eyes", "seasonal nasal congestion",
    "hives after eating", "swelling of lips", "swelling of tongue",
    "throat tightness", "difficulty breathing after exposure", "skin welts",
    "food-triggered stomach upset", "recurring infections", "frequent colds",
    "itchy throat", "skin flare after allergen exposure",
  ],
  Sleep: [
    "difficulty falling asleep", "waking up during the night", "loud snoring",
    "gasping during sleep", "daytime sleepiness", "restless legs at night",
    "nightmares", "teeth grinding at night", "sleepwalking", "unrefreshing sleep",
  ],
  Pediatric: [
    "poor feeding in infant", "excessive crying in infant",
    "delayed developmental milestones", "frequent ear infections in child",
    "failure to gain weight", "prolonged crying with pulled ear",
    "refusal to bear weight on a limb", "unusual lethargy in a child",
    "high fever with rash in a child", "repeated vomiting in an infant",
    "delayed speech in toddler",
  ],
};

export const COMMON_SYMPTOMS: string[] = Array.from(
  new Set(Object.values(SYMPTOM_CATEGORIES).flat())
);

export type Urgency = "Low" | "Medium" | "High";

export type Condition = {
  name: string;
  category: SymptomCategory;
  urgency: Urgency;
  symptoms: string[]; // must be exact strings from COMMON_SYMPTOMS
  description: string;
  advice: string;
};

export const CONDITIONS: Condition[] = [
  {
    name: "Common cold",
    category: "Respiratory",
    urgency: "Low",
    symptoms: ["runny nose", "nasal congestion", "sneezing", "sore throat", "cough", "low-grade fever", "fatigue"],
    description: "A mild viral infection of the nose and throat that typically resolves on its own within a week.",
    advice: "Rest, stay hydrated, and use over-the-counter remedies for symptom relief. See a doctor if symptoms worsen or last beyond 10 days.",
  },
  {
    name: "Influenza (flu)",
    category: "Respiratory",
    urgency: "Medium",
    symptoms: ["high fever", "chills", "generalized body ache", "fatigue", "dry cough", "sore throat", "headache"],
    description: "A viral respiratory infection that comes on quickly and causes more intense symptoms than a common cold.",
    advice: "Rest and fluids are key; antiviral medication may help if started early. Seek care if breathing becomes difficult.",
  },
  {
    name: "COVID-19 (possible)",
    category: "Respiratory",
    urgency: "Medium",
    symptoms: ["fever", "dry cough", "fatigue", "loss of sense of smell", "shortness of breath", "sore throat", "headache"],
    description: "A viral respiratory illness with a wide range of severity, from mild to serious.",
    advice: "Consider testing and isolating from others. Seek urgent care if shortness of breath worsens.",
  },
  {
    name: "Acute bronchitis",
    category: "Respiratory",
    urgency: "Low",
    symptoms: ["productive cough", "chest congestion", "wheezing", "fatigue", "sore throat"],
    description: "Inflammation of the airways, usually following a viral cold, causing a lingering cough.",
    advice: "Rest and fluids usually help; see a doctor if the cough lasts more than 3 weeks or you cough up blood.",
  },
  {
    name: "Pneumonia (possible)",
    category: "Respiratory",
    urgency: "High",
    symptoms: ["productive cough", "high fever", "chest pain", "shortness of breath", "rapid breathing", "chills"],
    description: "A lung infection that can range from mild to serious, especially in young children, older adults, or those with weakened immunity.",
    advice: "Seek prompt medical evaluation, especially if breathing is labored or fever is high.",
  },
  {
    name: "Asthma flare-up",
    category: "Respiratory",
    urgency: "Medium",
    symptoms: ["wheezing", "shortness of breath", "chest tightness", "whistling sound while breathing"],
    description: "A narrowing of the airways causing breathing difficulty, often triggered by allergens or exercise.",
    advice: "Use prescribed inhalers as directed; seek emergency care if breathing does not improve.",
  },
  {
    name: "Sinusitis",
    category: "Respiratory",
    urgency: "Low",
    symptoms: ["sinus pressure", "sinus headache", "nasal congestion", "postnasal drip", "sore throat"],
    description: "Inflammation of the sinuses, often following a cold, causing facial pressure and congestion.",
    advice: "Saline rinses and decongestants often help; see a doctor if symptoms persist beyond 10 days.",
  },
  {
    name: "Strep throat (possible)",
    category: "ENT & Eye",
    urgency: "Medium",
    symptoms: ["sore throat", "painful swallowing", "high fever", "swollen lymph nodes"],
    description: "A bacterial throat infection that often causes a sudden, severe sore throat.",
    advice: "A doctor can test for strep and prescribe antibiotics if confirmed — important to prevent complications.",
  },
  {
    name: "Tonsillitis",
    category: "ENT & Eye",
    urgency: "Medium",
    symptoms: ["sore throat", "painful swallowing", "fever", "bad breath", "swollen lymph nodes"],
    description: "Inflammation of the tonsils, often from a viral or bacterial infection.",
    advice: "See a doctor for evaluation, especially if swallowing becomes very difficult.",
  },
  {
    name: "Ear infection (otitis media)",
    category: "ENT & Eye",
    urgency: "Medium",
    symptoms: ["ear pain", "ear discharge", "hearing loss", "feeling of ear fullness", "fever"],
    description: "An infection of the middle ear, common in children, causing pain and sometimes fluid drainage.",
    advice: "See a doctor — many cases resolve with time or antibiotics if bacterial.",
  },
  {
    name: "Conjunctivitis (pink eye)",
    category: "ENT & Eye",
    urgency: "Low",
    symptoms: ["eye redness", "eye discharge", "itchy eyes", "watery eyes"],
    description: "Inflammation of the eye's surface, often viral, bacterial, or allergic.",
    advice: "Avoid touching or rubbing your eyes and wash hands frequently; see a doctor if vision is affected or pain is severe.",
  },
  {
    name: "Migraine",
    category: "Neurological",
    urgency: "Medium",
    symptoms: ["migraine", "sensitivity to light", "sensitivity to sound", "nausea", "headache"],
    description: "A neurological condition causing intense, often one-sided headaches, sometimes with visual changes.",
    advice: "Rest in a dark, quiet room; over-the-counter pain relief may help. See a doctor if migraines are frequent or severe.",
  },
  {
    name: "Tension headache",
    category: "Neurological",
    urgency: "Low",
    symptoms: ["headache", "neck stiffness", "irritability"],
    description: "A common type of headache often linked to stress or muscle tension.",
    advice: "Rest, hydration, and over-the-counter pain relief usually help.",
  },
  {
    name: "Stroke (possible emergency)",
    category: "Neurological",
    urgency: "High",
    symptoms: ["facial drooping", "slurred speech", "weakness on one side of body", "sudden confusion", "difficulty walking", "blurred vision"],
    description: "A medical emergency caused by disrupted blood flow to the brain.",
    advice: "Call emergency services immediately — rapid treatment significantly improves outcomes.",
  },
  {
    name: "Seizure disorder (possible)",
    category: "Neurological",
    urgency: "High",
    symptoms: ["seizure", "loss of consciousness", "muscle twitching", "sudden confusion"],
    description: "Abnormal electrical activity in the brain causing convulsions or altered awareness.",
    advice: "Seek urgent medical evaluation, especially for a first-time seizure.",
  },
  {
    name: "Vertigo / inner ear imbalance",
    category: "Neurological",
    urgency: "Medium",
    symptoms: ["vertigo", "dizziness", "loss of balance", "ringing in ears", "nausea"],
    description: "A sensation of spinning or imbalance, often linked to the inner ear.",
    advice: "See a doctor for evaluation; avoid driving until symptoms resolve.",
  },
  {
    name: "Anxiety disorder",
    category: "Mental health",
    urgency: "Medium",
    symptoms: ["anxiety", "excessive worry", "panic attacks", "racing thoughts", "difficulty falling asleep", "rapid heartbeat"],
    description: "A persistent pattern of excessive worry or fear that can affect daily life.",
    advice: "Speaking with a doctor or counselor can help; breathing exercises may ease acute episodes.",
  },
  {
    name: "Depression",
    category: "Mental health",
    urgency: "Medium",
    symptoms: ["persistent low mood", "sadness lasting weeks", "loss of interest in activities", "fatigue", "oversleeping", "social withdrawal"],
    description: "A mood disorder causing persistent sadness and loss of interest, lasting weeks or longer.",
    advice: "Reach out to a doctor or mental health professional — effective treatments are available.",
  },
  {
    name: "Insomnia",
    category: "Sleep",
    urgency: "Low",
    symptoms: ["difficulty falling asleep", "waking up during the night", "unrefreshing sleep", "daytime sleepiness"],
    description: "Persistent difficulty falling or staying asleep.",
    advice: "Good sleep hygiene often helps; see a doctor if it persists beyond a few weeks.",
  },
  {
    name: "Sleep apnea (possible)",
    category: "Sleep",
    urgency: "Medium",
    symptoms: ["loud snoring", "gasping during sleep", "daytime sleepiness", "unrefreshing sleep"],
    description: "A condition where breathing repeatedly stops and starts during sleep.",
    advice: "A sleep study can confirm this — talk to a doctor, especially if a partner notices breathing pauses.",
  },
  {
    name: "Gastroenteritis (stomach flu)",
    category: "Digestive",
    urgency: "Medium",
    symptoms: ["nausea", "vomiting", "diarrhea", "abdominal cramping", "low-grade fever"],
    description: "Inflammation of the stomach and intestines, usually from a viral or bacterial infection.",
    advice: "Stay hydrated with fluids and electrolytes; seek care if you can't keep fluids down or see blood in stool.",
  },
  {
    name: "GERD (acid reflux)",
    category: "Digestive",
    urgency: "Low",
    symptoms: ["heartburn", "acid reflux", "indigestion", "burping up food", "sore throat"],
    description: "A condition where stomach acid frequently flows back into the esophagus, causing irritation.",
    advice: "Avoiding trigger foods and not lying down right after eating often helps; see a doctor if symptoms are frequent.",
  },
  {
    name: "Irritable bowel syndrome (IBS)",
    category: "Digestive",
    urgency: "Low",
    symptoms: ["abdominal pain", "bloating", "constipation", "diarrhea", "excessive gas"],
    description: "A common digestive disorder affecting the large intestine, causing recurring abdominal discomfort.",
    advice: "Dietary changes often help; a doctor can help rule out other causes and suggest management strategies.",
  },
  {
    name: "Appendicitis (possible emergency)",
    category: "Digestive",
    urgency: "High",
    symptoms: ["lower abdominal pain", "nausea", "vomiting", "fever", "abdominal swelling"],
    description: "Inflammation of the appendix that can become a medical emergency if untreated.",
    advice: "Seek emergency care promptly, especially if pain worsens and shifts to the lower right abdomen.",
  },
  {
    name: "Peptic ulcer",
    category: "Digestive",
    urgency: "Medium",
    symptoms: ["upper abdominal pain", "indigestion", "nausea", "black tarry stool", "early feeling of fullness"],
    description: "A sore in the stomach lining or upper intestine, often linked to infection or long-term NSAID use.",
    advice: "See a doctor for evaluation — testing and treatment can resolve most cases.",
  },
  {
    name: "Constipation",
    category: "Digestive",
    urgency: "Low",
    symptoms: ["constipation", "bloating", "abdominal pain"],
    description: "Infrequent or difficult bowel movements.",
    advice: "Increasing fiber, fluids, and activity often helps; see a doctor if it persists or is accompanied by pain.",
  },
  {
    name: "Lactose intolerance",
    category: "Digestive",
    urgency: "Low",
    symptoms: ["bloating", "excessive gas", "diarrhea", "stomach cramps after eating", "lactose intolerance"],
    description: "Difficulty digesting lactose, the sugar found in dairy products.",
    advice: "Reducing dairy intake often resolves symptoms; a doctor can confirm with testing.",
  },
  {
    name: "Gallstones (possible)",
    category: "Digestive",
    urgency: "Medium",
    symptoms: ["upper abdominal pain", "nausea", "vomiting", "yellowing of skin", "yellowing of eyes"],
    description: "Hardened deposits in the gallbladder that can cause pain, especially after fatty meals.",
    advice: "See a doctor for imaging — treatment ranges from monitoring to surgery depending on severity.",
  },
  {
    name: "Hepatitis (possible)",
    category: "Digestive",
    urgency: "Medium",
    symptoms: ["yellowing of skin", "yellowing of eyes", "fatigue", "dark-colored urine", "pale-colored stool", "nausea"],
    description: "Inflammation of the liver, which can be caused by viruses, alcohol, or other factors.",
    advice: "See a doctor promptly for blood testing and evaluation.",
  },
  {
    name: "Urinary tract infection (UTI)",
    category: "Urinary & Reproductive",
    urgency: "Medium",
    symptoms: ["painful urination", "urgent need to urinate", "cloudy urine", "burning sensation during urination", "lower back pain with urination"],
    description: "A bacterial infection of the urinary tract, more common in women.",
    advice: "See a doctor — antibiotics usually resolve it quickly. Seek urgent care if fever or flank pain develops.",
  },
  {
    name: "Kidney stones (possible)",
    category: "Urinary & Reproductive",
    urgency: "High",
    symptoms: ["flank pain", "blood in urine", "painful urination", "nausea", "vomiting"],
    description: "Hard mineral deposits that form in the kidneys and can cause severe pain when passing.",
    advice: "Seek prompt medical care — pain management and imaging are typically needed.",
  },
  {
    name: "Kidney infection (possible)",
    category: "Urinary & Reproductive",
    urgency: "High",
    symptoms: ["flank pain", "high fever", "painful urination", "nausea", "chills"],
    description: "A more serious infection that has spread to the kidneys, often from an untreated UTI.",
    advice: "Seek prompt medical care — this typically requires antibiotics and close monitoring.",
  },
  {
    name: "Overactive bladder",
    category: "Urinary & Reproductive",
    urgency: "Low",
    symptoms: ["urgent need to urinate", "frequent urination", "urinary incontinence"],
    description: "A condition causing a sudden, hard-to-control urge to urinate.",
    advice: "A doctor can discuss lifestyle changes and treatment options.",
  },
  {
    name: "Benign prostatic hyperplasia (possible)",
    category: "Urinary & Reproductive",
    urgency: "Low",
    symptoms: ["frequent urination", "weak urine stream", "difficulty urinating", "low urine output"],
    description: "Non-cancerous enlargement of the prostate gland, common in older men, affecting urination.",
    advice: "See a doctor for evaluation and management options.",
  },
  {
    name: "Menstrual cramps (dysmenorrhea)",
    category: "Urinary & Reproductive",
    urgency: "Low",
    symptoms: ["painful menstrual cramps", "lower abdominal pain in women", "irregular menstrual periods"],
    description: "Pain associated with the menstrual cycle, ranging from mild to severe.",
    advice: "Heat and over-the-counter pain relief often help; see a doctor if pain is severe or disrupts daily life.",
  },
  {
    name: "Polycystic ovary syndrome (possible)",
    category: "Urinary & Reproductive",
    urgency: "Low",
    symptoms: ["irregular menstrual periods", "unusually heavy periods", "acne breakouts", "hair thinning", "unexplained weight gain"],
    description: "A hormonal condition that can affect periods, skin, and metabolism.",
    advice: "See a doctor for hormonal testing and management options.",
  },
  {
    name: "Vaginal yeast infection",
    category: "Urinary & Reproductive",
    urgency: "Low",
    symptoms: ["vaginal discharge", "vaginal itching", "pain during intercourse"],
    description: "A common fungal infection causing itching and discharge.",
    advice: "Over-the-counter antifungal treatments often help; see a doctor if symptoms don't improve.",
  },
  {
    name: "Pelvic inflammatory disease (possible)",
    category: "Urinary & Reproductive",
    urgency: "High",
    symptoms: ["pelvic pain", "abnormal vaginal bleeding", "vaginal discharge", "fever", "pain during intercourse"],
    description: "An infection of the female reproductive organs that can lead to complications if untreated.",
    advice: "Seek prompt medical care — early antibiotic treatment prevents complications.",
  },
  {
    name: "Possible pregnancy",
    category: "Urinary & Reproductive",
    urgency: "Medium",
    symptoms: ["missed period", "nausea", "breast pain", "fatigue", "unexplained weight gain"],
    description: "These symptoms together can be early signs worth confirming with a test and a doctor.",
    advice: "Consider a pregnancy test and follow up with a doctor for confirmation and care planning.",
  },
  {
    name: "Erectile dysfunction",
    category: "Urinary & Reproductive",
    urgency: "Low",
    symptoms: ["erectile difficulty"],
    description: "Difficulty achieving or maintaining an erection, which can have physical or psychological causes.",
    advice: "A doctor can help identify underlying causes and discuss treatment options.",
  },
  {
    name: "Allergic rhinitis (hay fever)",
    category: "Allergy & Immune",
    urgency: "Low",
    symptoms: ["sneezing fits", "itchy watery eyes", "seasonal nasal congestion", "itchy throat"],
    description: "An allergic reaction to airborne particles like pollen or dust, affecting the nose and eyes.",
    advice: "Antihistamines and avoiding triggers often help; see a doctor if symptoms are persistent or severe.",
  },
  {
    name: "Anaphylaxis (severe allergic reaction — emergency)",
    category: "Allergy & Immune",
    urgency: "High",
    symptoms: ["swelling of lips", "swelling of tongue", "throat tightness", "difficulty breathing after exposure", "hives after eating", "skin welts"],
    description: "A severe, rapid, whole-body allergic reaction that can be life-threatening.",
    advice: "This is a medical emergency — use an epinephrine auto-injector if available and call emergency services immediately.",
  },
  {
    name: "Food allergy",
    category: "Allergy & Immune",
    urgency: "Medium",
    symptoms: ["hives after eating", "food-triggered stomach upset", "swelling of lips", "itching"],
    description: "An immune reaction to a specific food, ranging from mild to severe.",
    advice: "Avoid the suspected food and see a doctor for allergy testing, especially if reactions are worsening.",
  },
  {
    name: "Contact dermatitis",
    category: "Skin",
    urgency: "Low",
    symptoms: ["skin rash", "itching", "skin redness", "dry skin"],
    description: "Skin irritation caused by contact with an allergen or irritant.",
    advice: "Identifying and avoiding the trigger usually resolves it; a doctor can help with persistent cases.",
  },
  {
    name: "Eczema",
    category: "Skin",
    urgency: "Low",
    symptoms: ["dry skin", "itching", "skin redness", "eczema flare-up"],
    description: "A chronic condition causing dry, itchy, and inflamed skin.",
    advice: "Moisturizing regularly and avoiding triggers helps; a doctor can prescribe treatment for flare-ups.",
  },
  {
    name: "Cellulitis (possible)",
    category: "Skin",
    urgency: "High",
    symptoms: ["warm and swollen skin patch", "skin redness", "fever", "non-healing skin wound"],
    description: "A bacterial skin infection that can spread quickly if untreated.",
    advice: "Seek prompt medical care, especially if redness is spreading or you develop a fever.",
  },
  {
    name: "Fungal skin infection",
    category: "Skin",
    urgency: "Low",
    symptoms: ["athlete's foot", "jock itch", "skin peeling", "itching"],
    description: "A common fungal infection of the skin, often in warm, moist areas.",
    advice: "Over-the-counter antifungal treatments usually work; see a doctor if it doesn't improve.",
  },
  {
    name: "Acne",
    category: "Skin",
    urgency: "Low",
    symptoms: ["acne breakouts", "oily skin", "skin redness"],
    description: "A common skin condition caused by clogged hair follicles, often related to hormones.",
    advice: "Consistent skincare helps; a doctor or dermatologist can prescribe treatment for stubborn cases.",
  },
  {
    name: "Shingles (possible)",
    category: "Skin",
    urgency: "Medium",
    symptoms: ["skin rash", "blisters", "skin redness", "muscle pain"],
    description: "A painful rash caused by reactivation of the chickenpox virus, usually in a band on one side of the body.",
    advice: "See a doctor promptly — early antiviral treatment can reduce severity and complications.",
  },
  {
    name: "Osteoarthritis",
    category: "Musculoskeletal",
    urgency: "Low",
    symptoms: ["joint pain", "joint stiffness in the morning", "limited range of motion", "cracking joints"],
    description: "Wear-and-tear joint changes that cause pain and stiffness, common with age.",
    advice: "Gentle exercise and pain management help; see a doctor for a management plan.",
  },
  {
    name: "Rheumatoid arthritis (possible)",
    category: "Musculoskeletal",
    urgency: "Medium",
    symptoms: ["joint pain", "joint swelling", "joint stiffness in the morning", "fatigue", "joint warmth to touch"],
    description: "An autoimmune condition causing joint inflammation, often in a symmetric pattern.",
    advice: "See a doctor for evaluation — early treatment helps prevent joint damage.",
  },
  {
    name: "Muscle strain",
    category: "Musculoskeletal",
    urgency: "Low",
    symptoms: ["muscle pain", "muscle stiffness after rest", "limited range of motion", "swelling in a limb"],
    description: "An injury to a muscle from overuse or sudden strain.",
    advice: "Rest, ice, and gentle stretching usually help; see a doctor if pain is severe or doesn't improve.",
  },
  {
    name: "Sciatica",
    category: "Musculoskeletal",
    urgency: "Medium",
    symptoms: ["lower back pain", "numbness in limbs", "tingling sensation", "muscle weakness"],
    description: "Pain radiating along the sciatic nerve, often from the lower back to the leg.",
    advice: "See a doctor for evaluation — most cases improve with conservative treatment.",
  },
  {
    name: "Gout (possible)",
    category: "Musculoskeletal",
    urgency: "Medium",
    symptoms: ["joint pain", "joint redness", "joint swelling", "joint warmth to touch"],
    description: "A form of arthritis caused by uric acid crystal buildup, often affecting the big toe.",
    advice: "See a doctor — dietary changes and medication can manage flare-ups.",
  },
  {
    name: "Heart attack (possible emergency)",
    category: "Cardiovascular",
    urgency: "High",
    symptoms: ["chest pain", "chest pressure", "chest pain radiating to arm", "shortness of breath", "cold sweats", "nausea"],
    description: "A medical emergency caused by blocked blood flow to the heart muscle.",
    advice: "Call emergency services immediately — do not drive yourself.",
  },
  {
    name: "Arrhythmia (possible)",
    category: "Cardiovascular",
    urgency: "Medium",
    symptoms: ["palpitations", "rapid heartbeat", "irregular heartbeat", "dizziness", "fainting during exercise"],
    description: "An irregular heartbeat that can range from harmless to serious.",
    advice: "See a doctor for an evaluation, especially if accompanied by fainting or chest discomfort.",
  },
  {
    name: "Deep vein thrombosis (possible)",
    category: "Cardiovascular",
    urgency: "High",
    symptoms: ["swelling in legs", "leg cramps at night", "calf pain", "warm and swollen skin patch"],
    description: "A blood clot in a deep vein, usually in the leg, that can be dangerous if it travels to the lungs.",
    advice: "Seek prompt medical care, especially with one-sided leg swelling and pain.",
  },
  {
    name: "Hypertension (high blood pressure)",
    category: "Cardiovascular",
    urgency: "Low",
    symptoms: ["headache", "dizziness", "high blood pressure readings", "nosebleed"],
    description: "Elevated blood pressure that often has no symptoms but raises long-term health risks.",
    advice: "Regular monitoring and a doctor's guidance on lifestyle or medication is recommended.",
  },
  {
    name: "Anemia (possible)",
    category: "General",
    urgency: "Low",
    symptoms: ["fatigue", "weakness", "dizziness", "shortness of breath"],
    description: "A condition where the body lacks enough healthy red blood cells to carry oxygen efficiently.",
    advice: "A simple blood test can confirm this — see a doctor, especially if fatigue is persistent.",
  },
  {
    name: "Hypothyroidism (possible)",
    category: "Endocrine & Metabolic",
    urgency: "Low",
    symptoms: ["fatigue", "unexplained weight gain", "cold intolerance", "hair thinning", "dry skin"],
    description: "An underactive thyroid gland that can slow down the body's metabolism.",
    advice: "A blood test can confirm this — see a doctor for evaluation and possible treatment.",
  },
  {
    name: "Hyperthyroidism (possible)",
    category: "Endocrine & Metabolic",
    urgency: "Medium",
    symptoms: ["unexplained weight loss", "heat intolerance", "rapid heartbeat", "hand tremor", "excessive sweating without exertion"],
    description: "An overactive thyroid gland that can speed up the body's metabolism.",
    advice: "See a doctor for blood testing — treatment options are effective.",
  },
  {
    name: "Type 2 diabetes (possible)",
    category: "Endocrine & Metabolic",
    urgency: "Medium",
    symptoms: ["excessive thirst", "frequent urination at night", "increased hunger", "fatigue after meals", "slow wound healing", "unexplained weight loss"],
    description: "A condition where the body has trouble regulating blood sugar levels.",
    advice: "See a doctor for blood sugar testing — early management makes a big difference.",
  },
  {
    name: "Meningitis (possible emergency)",
    category: "Neurological",
    urgency: "High",
    symptoms: ["severe sudden headache", "neck stiffness", "high fever", "sensitivity to light", "sudden confusion"],
    description: "A serious infection of the membranes surrounding the brain and spinal cord.",
    advice: "This is a medical emergency — seek immediate care, especially with neck stiffness and fever together.",
  },
  {
    name: "Sepsis (possible emergency)",
    category: "General",
    urgency: "High",
    symptoms: ["high fever", "chills", "rapid heartbeat", "rapid breathing", "sudden confusion", "weakness"],
    description: "A life-threatening response to infection that can rapidly affect multiple organs.",
    advice: "This is a medical emergency — seek immediate care, especially if you have a known infection and these symptoms develop.",
  },
  {
    name: "Childhood ear infection or fever illness",
    category: "Pediatric",
    urgency: "Medium",
    symptoms: ["high fever with rash in a child", "prolonged crying with pulled ear", "unusual lethargy in a child"],
    description: "Fever and ear-pulling in a young child can point to an ear infection or another childhood illness.",
    advice: "See a pediatrician, especially for infants under 3 months with any fever.",
  },
  {
    name: "Failure to thrive (possible, infant)",
    category: "Pediatric",
    urgency: "Medium",
    symptoms: ["poor feeding in infant", "failure to gain weight", "excessive crying in infant"],
    description: "When an infant isn't gaining weight or feeding as expected for their age.",
    advice: "See a pediatrician for growth assessment and feeding evaluation.",
  },
  {
    name: "Croup (possible, child)",
    category: "Pediatric",
    urgency: "Medium",
    symptoms: ["barking cough", "whistling sound while breathing", "hoarseness", "fever"],
    description: "A childhood respiratory illness causing a distinctive barking cough, from airway swelling.",
    advice: "Cool or humid air often helps; seek urgent care if breathing becomes labored.",
  },
  {
    name: "Infant reflux (possible)",
    category: "Pediatric",
    urgency: "Low",
    symptoms: ["repeated vomiting in an infant", "poor feeding in infant", "excessive crying in infant"],
    description: "Frequent spit-up or vomiting in infants, often outgrown but worth monitoring.",
    advice: "See a pediatrician if vomiting is forceful, frequent, or affecting weight gain.",
  },
];
